import { z } from 'zod';

export const InvestmentFormSchema = z.object({
    name: z.string().min(1, "Nazwa inwestycji jest wymagana."),
    contract_signing_date: z.string().optional(),
    completion_deadline: z.string().optional(),
    contract_annex: z.string().optional(),
    notes: z.string().optional(),
    construction_site_contact: z.string().optional(),
    responsible_person: z.string().optional(),
    supervision_inspector: z.string().optional(),
    journal_registration: z.number().optional(),
    work_start_notification: z.number().optional(),
    construction_board: z.number().optional(),
    building_project_minor_changes: z.string().optional(),
    execution_project: z.string().optional(),
    string_design: z.string().optional(),
    medium_voltage_connection_scope: z.string().optional(),
    acceptance_protocol: z.string().optional(),
    osd_acceptance_documentation: z.string().optional(),
    client_acceptance_documentation: z.string().optional(),
    power_plant_connection: z.number().optional(),
    psp_notification: z.number().optional(),
    pinb_notification: z.number().optional(),
    surveyor_stakeout: z.string().optional(),
    surveyor_inventory: z.string().optional(),
    fence_delivery: z.string().optional(),
    fence_construction: z.string().optional(),
    site_security: z.string().optional(),
    structure_delivery: z.string().optional(),
    piling: z.string().optional(),
    structure_assembly: z.string().optional(),
    module_delivery: z.string().optional(),
    module_installation: z.string().optional(),
    assembly_materials: z.string().optional(),
    ac_wiring_routes: z.string().optional(),
    dc_wiring_routes: z.string().optional(),
    medium_voltage_wiring_routes: z.string().optional(),
    transformer_station: z.string().optional(),
    telematics: z.string().optional(),
    cctv: z.string().optional(),
    equipotential_connections: z.string().optional(),
});
